<?php

/**
 * @file
 * Install, update and uninstall functions for the twitter module.
 *
 */

/**
 * Don't default to TinyURL any more.
 */
function twitter_post_update_7300() {
  if (variable_get('twitter_post_default_format', NULL) == 'New post: !title !tinyurl') {
    variable_set('twitter_post_default_format', "New post: !title !url-alias");
  }
  return t('Twitter Post now defaults to using aliases, not TinyURL.');
}
