<?php
/**
 * @file
 *
 * Hook implementations for twitter_post module.
 */

// Field API definitions.
require_once 'twitter_post.field.inc';

/**
 * Implements hook_permission().
 */
function twitter_post_permission() {
  return array(
    'post to twitter' => array(
      'title' => t('Post a message to Twitter'),
    ),
  );
}

/**
 * Implementation of hook_entity_insert().
 *
 * Intercepts newly created entities and posts notices to Twitter.
 */
function twitter_post_entity_insert($entity, $type) {
  // First we find twitter_post fields.
  $fields_info = field_info_instances($type, $entity->type);
  foreach ($fields_info as $field_name => $value) {
    $field_info = field_info_field($field_name);
    if ($field_info['type'] == 'twitter_post') {
      // Extract data out of each field.
      $status = $entity->{$field_name}[$entity->language][0]['status'];
      $message = $entity->{$field_name}[$entity->language][0]['message'];
      $twitter_account = entity_load_single('twitter_account', $entity->{$field_name}[$entity->language][0]['account']);
      // Post to Twitter if the status checkbox is active.
      if ($status) {
        module_load_include('inc', 'twitter');
        $replacements = array(
          '!title' => $entity->title,
          '!url' => url('node/' . $entity->nid, array('absolute' => TRUE, 'alias' => TRUE)),
          '!url-alias' => url('node/' . $entity->nid, array('absolute' => TRUE)),
          '!user' => $entity->name,
        );

        // Only generate the shortened URL if it's going to be used. No sense
        // burning through TinyURLs without a good reason.
        if (strstr($message, '!tinyurl') !== FALSE) {
          $replacements['!tinyurl'] = twitter_shorten_url(url('node/' . $entity->nid, array('absolute' => TRUE)));
        }

        $message = strtr($message, $replacements);
        $status = twitter_set_status($twitter_account, $message);
        if ($status) {
          drupal_set_message(t('Successfully posted to Twitter: <a href="@status" target="_blank">@status</a>', array(
            '@status' => _twitter_status_url($status),
          )));
        }
      }
    }
  }
}

/**
 * Implementation of hook_entity_update().
 */
function twitter_post_entity_update($entity, $type) {
  twitter_post_entity_insert($entity, $type);
}
